In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load csv data into dataframe
import pandas as pd
accounts_df = pd.read_csv('..//data/accounts.csv')
categories_df = pd.read_csv('..//data/categories.csv')
transactions_df = pd.read_csv('..//data/transactions.csv')

In [5]:
categories_df

    cat_id           name     type
0        1           Rent  expense
1        2      Groceries  expense
2        3      Utilities  expense
3        4      Transport  expense
4        5     Dining Out  expense
5        6  Entertainment  expense
6        7     Healthcare  expense
7        8       Shopping  expense
8        9  Subscriptions  expense
9       10         Salary   income
10      11      Freelance   income
11      12     Investment   income

In [4]:
accounts_df

   account_id              name  balance
0           1  Checking Account      0.0
1           2   Savings Account      0.0

In [3]:
transactions_df

     transaction_id  account_id  cat_id   amount        date       description
0                 1           1       1  1500.00  2025-01-01      Monthly rent
1                 2           1       3   130.00  2025-01-03  Electric & water
2                 3           1       9    43.00  2025-01-05  Streaming & apps
3                 4           1       2    84.00  2025-01-24       Grocery run
4                 5           1       2    62.33  2025-01-08       Grocery run
..              ...         ...     ...      ...         ...               ...
322             323           2       8    59.89  2025-12-08          Shopping
323             324           1      10  4500.00  2025-12-15    Monthly salary
324             325           1      10  4500.00  2025-12-28    Monthly salary
325             326           1      11   352.38  2025-12-05    Freelance work
326             327           2      12   314.39  2025-12-07          Dividend

[327 rows x 6 columns]

In [ ]:
# What we want to visualize
# 1. Total spending by category
# 2. Spending over time
# 3. Account balances

In [ ]:
# Total spending by category